version: '3.8'

services:
  neo4j:
    image: neo4j:5.18.0
    container_name: safeplate-neo4j
    ports:
      - "7474:7474" # HTTP port (for the visual browser)
      - "7687:7687" # Bolt port (for the Python script to connect)
    environment:
      - NEO4J_AUTH=neo4j/safeplate123 # Sets the username and password
    volumes:
      - ./neo4j_data:/data # Saves the database to your local folder so you don't lose it
      - ./data:/var/lib/neo4j/import # Allows Neo4j to directly read our generated CSV files
